# Generated by Django 5.2.8 on 2025-11-13 05:59

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_classsession_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='token',
            field=models.CharField(default=attendance.models.generate_unique_token, editable=False, max_length=64, unique=True),
        ),
    ]
